version: "3.7"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    hostname: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker.network=app_dev-network"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      dev-network:

  finance-app-backend:
    image: fernandocanabarroahnert/finance-app-backend
    container_name: finance-app-backend
    restart: always
    depends_on:
      - traefik
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWK_SET_URI: ${JWK_SET_URI}
      ISSUER_URI: ${ISSUER_URI}
      CORS_ORIGINS: ${CORS_ORIGINS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo.rule=Host(`finance-app.fernandocanabarrodev.tech`)"
      - "traefik.http.routers.todo.entrypoints=websecure"
      - "traefik.http.routers.todo.tls.certresolver=letsencrypt"
      - "traefik.http.services.todo.loadbalancer.server.port=8080"
    networks:
      dev-network:

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - keycloak_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      - dev-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.2
    command: start-dev --import-realm
    restart: always
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: keycloak-mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak.fernandocanabarrodev.tech
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    volumes:
      - keycloak_data:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.fernandocanabarrodev.tech`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  letsencrypt:
  keycloak_mysql_data:
  keycloak_data: